# Generated by Django 4.2.5 on 2023-09-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0007_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/products/')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooltables.products')),
            ],
        ),
    ]
