# Generated by Django 4.2.5 on 2023-09-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0008_productpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
