# Generated by Django 4.2.5 on 2023-09-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0009_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPage',
        ),
    ]
