# Generated by Django 4.2.5 on 2023-09-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0010_delete_productpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='uploads/products/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pooltables.category')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pooltables.products')),
            ],
        ),
    ]
