# Generated by Django 4.2.6 on 2023-10-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0012_photo_review_rating_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='uploads/products/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pooltables.customer')),
            ],
        ),
    ]
