# Generated by Django 4.2.6 on 2023-10-13 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pooltables.customer'),
        ),
    ]
