# Generated by Django 4.2.6 on 2023-10-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0014_remove_profile_images_customer_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
