# Generated by Django 4.2.6 on 2023-10-13 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0015_rename_first_name_customer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='images',
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='users'),
            preserve_default=False,
        ),
    ]
