# Generated by Django 4.2.6 on 2023-10-13 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0016_remove_customer_images_profile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
