# Generated by Django 4.2.6 on 2023-10-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooltables', '0019_customers_alter_like_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
